name: Linode Engineering
description: Blog posts from Linode engineerings about engineering at Linode
url: https://engineering.linode.com
gems: [jekyll-paginate]
sass:
    style: compressed
    sass_dir: css
paginate: 5
paginate_path: "/archive/:num/"
future: true
plugins_dir: ./_plugins